### ISSUE TITLE
Mlrun 3s Values not being used, wanting too use external selfhosted minio

### ISSUE THREAD

**Issue by Ewoodss** [mlrun/ce#161]
I am trying too set up mlrun, and want too use my own external already hosted minio.
this because this minio instance already has most of my storage assigned.

```yaml
mlrun:
  enabled: true
  storage: s3
  s3:
    region: us-east-1
    regionEndpoint: 127.0.0.1:9000
    bucket: mlrun
    encrypt: false
    secure: true

minio:
  enabled: false
  rootUser: external-user
  rootPassword: external-password

pipelines:
  enabled: true
  minio:
    enabled: false
    accessKey: external-user
    secretKey: external-password
    endpointPort: 9000
    bucket: "mlrun"
```

> 127.0.0.1 is a example what i have their is my internal ip adress for my own minio instance

is seems the minio endpoint still get's set too the old servicename which doesn't exist when setting the internal minio to enable: false
